
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Point;
import java.awt.Toolkit;
import java.lang.reflect.Method;
import java.util.Arrays;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CalAboutBox.java
 *
 * Created on 27 Dec, 2009, 2:05:09 PM
 */



/**
 *
 * @author suhas
 */
public class CalAboutBox extends javax.swing.JDialog implements CalInterface {

    /** Creates new form CalAboutBox */
    public CalAboutBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         Dimension screenSize =
        Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(new Point((screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2));
    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labVersion = new javax.swing.JLabel();
        labVersionValue = new javax.swing.JLabel();
        labAuthor = new javax.swing.JLabel();
        labAuthorValue = new javax.swing.JLabel();
        labAuthorWebPage = new javax.swing.JLabel();
        labAuthorWebPageValue = new javax.swing.JLabel();
        labToolWebPage = new javax.swing.JLabel();
        labToolWebPageValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/41-4145.jpg"))); // NOI18N
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel2.setText(APP_NAME);
        jPanel1.add(jLabel2);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/41-4145.jpg"))); // NOI18N
        jPanel1.add(jLabel3);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridLayout(4, 4));

        labVersion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labVersion.setText("Version : ");
        jPanel3.add(labVersion);

        labVersionValue.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labVersionValue.setText(VERSION);
        jPanel3.add(labVersionValue);

        labAuthor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labAuthor.setText("Author :");
        jPanel3.add(labAuthor);

        labAuthorValue.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labAuthorValue.setText(AUTHORandEMAILID);
        jPanel3.add(labAuthorValue);

        labAuthorWebPage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labAuthorWebPage.setText("Author's WebPage : ");
        jPanel3.add(labAuthorWebPage);

        labAuthorWebPageValue.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labAuthorWebPageValue.setText(AUTH_HOMEPAGE);
        labAuthorWebPageValue.setToolTipText("Open link");
        labAuthorWebPageValue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labAuthorWebPageValueMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labAuthorWebPageValueMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labAuthorWebPageValueMouseEntered(evt);
            }
        });
        jPanel3.add(labAuthorWebPageValue);

        labToolWebPage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labToolWebPage.setText("Home Page : ");
        jPanel3.add(labToolWebPage);

        labToolWebPageValue.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labToolWebPageValue.setText(HOMEPAGE);
        labToolWebPageValue.setToolTipText("Open link");
        labToolWebPageValue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labToolWebPageValueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labToolWebPageValueMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labToolWebPageValueMousePressed(evt);
            }
        });
        jPanel3.add(labToolWebPageValue);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(238, 238, 238));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("A Calender generally has 12 sheets of paper isn't? \nWell how about an entire calender in just a single sheet of paper?\nHere is a simple tool for exactly that purpose\nJust select the year and hit the print button.");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labAuthorWebPageValueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labAuthorWebPageValueMousePressed
        JLabel l = (JLabel) evt.getSource();
        System.out.println("Pressed");
        System.out.println(l.getFont());
        System.out.println(l.getColorModel());
        openURL(l.getText().trim());
    }//GEN-LAST:event_labAuthorWebPageValueMousePressed

    private void labAuthorWebPageValueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labAuthorWebPageValueMouseEntered
        JLabel l = (JLabel) evt.getSource();
        customFontAndColor(l);
    }//GEN-LAST:event_labAuthorWebPageValueMouseEntered

    private void labAuthorWebPageValueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labAuthorWebPageValueMouseExited
        JLabel l = (JLabel) evt.getSource();
        defaultFontAndColor(l);
    }//GEN-LAST:event_labAuthorWebPageValueMouseExited

    private void labToolWebPageValueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labToolWebPageValueMouseEntered
        JLabel l = (JLabel) evt.getSource();
        customFontAndColor(l);
    }//GEN-LAST:event_labToolWebPageValueMouseEntered

    private void labToolWebPageValueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labToolWebPageValueMouseExited
        JLabel l = (JLabel) evt.getSource();
        defaultFontAndColor(l);
    }//GEN-LAST:event_labToolWebPageValueMouseExited

    private void labToolWebPageValueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labToolWebPageValueMousePressed
        JLabel l = (JLabel) evt.getSource();
        System.out.println("Pressed");
        System.out.println(l.getFont());
        System.out.println(l.getColorModel());
        openURL(l.getText().trim());
    }//GEN-LAST:event_labToolWebPageValueMousePressed

public void customFontAndColor(JLabel l)
{
    setCursor(Cursor.getPredefinedCursor(12));
    l.setFont(new Font("Tahoma", Font.BOLD, 13));
    l.setForeground(new Color(0, 0, 255));
}

public void defaultFontAndColor(JLabel l)
{
    setCursor(Cursor.getDefaultCursor());
    l.setFont(new Font("Tahoma", Font.PLAIN, 13));
    l.setForeground(new Color(0, 0, 0));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labAuthor;
    private javax.swing.JLabel labAuthorValue;
    private javax.swing.JLabel labAuthorWebPage;
    private javax.swing.JLabel labAuthorWebPageValue;
    private javax.swing.JLabel labToolWebPage;
    private javax.swing.JLabel labToolWebPageValue;
    private javax.swing.JLabel labVersion;
    private javax.swing.JLabel labVersionValue;
    // End of variables declaration//GEN-END:variables

      static final String[] browsers = { "firefox", "opera", "konqueror", "epiphany",
      "seamonkey", "galeon", "kazehakase", "mozilla", "netscape" };

   public static void openURL(String url) {
      String osName = System.getProperty("os.name");
      try {
         if (osName.startsWith("Mac OS")) {
            Class<?> fileMgr = Class.forName("com.apple.eio.FileManager");
            Method openURL = fileMgr.getDeclaredMethod("openURL",
               new Class[] {String.class});
            openURL.invoke(null, new Object[] {url});
            }
         else if (osName.startsWith("Windows"))
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + url);
         else { //assume Unix or Linux
            boolean found = false;
            for (String browser : browsers)
               if (!found) {
                  found = Runtime.getRuntime().exec(
                     new String[] {"which", browser}).waitFor() == 0;
                  if (found)
                     Runtime.getRuntime().exec(new String[] {browser, url});
                  }
            if (!found)
               throw new Exception(Arrays.toString(browsers));
            }
         }
      catch (Exception e) {
         JOptionPane.showMessageDialog(null,
            "Error attempting to launch web browser\n" + e.toString());
         }
      }

}
